[package]
name = "kmerator-rs"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "kmerators"
path = "src/main.rs"

[dependencies]
ahash = "0.8"
anyhow = "1.0"
bincode = { version = "2.0", features = ["serde"] }
clap = { version = "4.5", features = ["derive", "wrap_help"] }
crossbeam-channel = "0.5"
dirs = "6.0"
flate2 = "1.1"
hashbrown = { version = "0.16", features = ["serde"] }
helicase = { version = "0.1.1", features = ["packed-seq"] }
num_cpus = "1.17"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
simd-minimizers = "2.3"
tempfile = "3.23"
thiserror = "2.0"
time = { version = "0.3", features = ["formatting", "local-offset"] }

[features]
default = ["portable"]
portable = ["simd-minimizers/scalar"]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"

[profile.dev]
opt-level = 1
lto = "thin"
